name: Reusable workflow. Using to build, test and push API

on:
  workflow_call:
    inputs:
      MODULE_NAME:
        description: "Using for choice specified module when build application. 
                        If not present - used project directory for build and test"
        default: .
        type: string
      DOCKERHUB_REPOSITORY:
        description: "Using for deploy docker image to DockerHub (e.g., username/repository)"
        required: true
        type: string
      BOOT_JAR_NAME:
        description: "Using for start docker container."
        required: true
        type: string
      IS_TEST_ENABLED:
        description: "Using for start test before pushing to DockerHub if value is true."
        required: true
        type: boolean
      IS_DOCKERHUB_PUSH_ENABLED:
        description: "Using for disable pushing to DockerHub if value is false."
        required: true
        type: boolean
      IS_COPY_DOCKERFILE:
        description: "Using for copy default dockerfile from https://github.com/ArbinaHQ/arbina-github-runner/tree/master/docker/api."
        required: true
        type: boolean
      IS_COPY_DOCKER_DIRECTORY:
        description: "Using for copy default docker directory (entrypoint, cron, healthcheck) from https://github.com/ArbinaHQ/arbina-github-runner/tree/master/docker/api."
        required: true
        type: boolean
      JAVA_VERSION:
        description: "Using for set version Java in build"
        default: "25"
        required: false
        type: string
      GRADLE_VERSION:
        description: "Using for set version Gradle in build"
        default: "9.2.1"
        required: false
        type: string
      SPRING_BOOT_LOADER:
        description: "Used for run spring boot application"
        default: "org.springframework.boot.loader.launch.JarLauncher"
        required: false
        type: string

jobs:
  api-multi-module-workflow:
    runs-on: custom
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK ${{ inputs.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
          distribution: 'zulu'

      - name: Setup Gradle ${{ inputs.GRADLE_VERSION }}
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{ inputs.GRADLE_VERSION }}
          cache-read-only: false
          cache-disabled: false

      - name: Build application
        if: ${{ !inputs.IS_TEST_ENABLED }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_CAN_READ_PACKAGES || secrets.GH_DEPBOT_TOKEN_CAN_READ_PACKAGES }}
          GITHUB_USERNAME: ${{ secrets.GH_USER_CAN_READ_PACKAGES || secrets.GH_DEPBOT_USER_CAN_READ_PACKAGES }}
          BOOT_JAR_NAME: ${{ inputs.BOOT_JAR_NAME }}
        run: gradle bootJar -p ${{ inputs.MODULE_NAME }} --parallel --no-daemon

      - name: Build and test application
        if: ${{ inputs.IS_TEST_ENABLED }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_CAN_READ_PACKAGES || secrets.GH_DEPBOT_TOKEN_CAN_READ_PACKAGES }}
          GITHUB_USERNAME: ${{ secrets.GH_USER_CAN_READ_PACKAGES || secrets.GH_DEPBOT_USER_CAN_READ_PACKAGES }}
          BOOT_JAR_NAME: ${{ inputs.BOOT_JAR_NAME }}
        run: gradle bootJar test -p ${{ inputs.MODULE_NAME }} --parallel --no-daemon

      - name: Copy docker directory
        if: ${{ inputs.IS_COPY_DOCKER_DIRECTORY }}
        run: cp -r /docker/api-v1/docker ./
        working-directory: ${{ inputs.MODULE_NAME }}

      - name: Copy dockerfile
        if: ${{ inputs.IS_COPY_DOCKERFILE }}
        run: cp /docker/api-v1/Dockerfile ./
        working-directory: ${{ inputs.MODULE_NAME }}

      - name: Set up Docker Buildx
        if: ${{ inputs.IS_DOCKERHUB_PUSH_ENABLED }}
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: ${{ inputs.IS_DOCKERHUB_PUSH_ENABLED }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.ARBINA_AVIARADAR_ECR_USERNAME }}
          password: ${{ secrets.ARBINA_AVIARADAR_ECR_PASSWORD }}

      - name: Login to ECR
        if: ${{ inputs.IS_ECR_PUSH_ENABLED }}
        id: login-ecr
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ARBINA_ECR_REGISTRY }}
          username: ${{ secrets.ARBINA_ECR_USERNAME }}
          password: ${{ secrets.ARBINA_ECR_PASSWORD }}

      - name: Docker meta
        if: ${{ inputs.IS_DOCKERHUB_PUSH_ENABLED }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.DOCKERHUB_REPOSITORY }}
          tags: |
            type=raw,value=latest
            type=sha,prefix=,format=long

      - name: Build and push Docker image
        if: ${{ inputs.IS_DOCKERHUB_PUSH_ENABLED }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.MODULE_NAME }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            IMAGE_TAG=${{ github.sha }}
            JAVA_VERSION=${{ inputs.JAVA_VERSION }}
            BOOT_JAR_NAME=${{ inputs.BOOT_JAR_NAME }}
            SPRING_BOOT_LOADER=${{ inputs.SPRING_BOOT_LOADER }}
          cache-from: type=registry,ref=${{ inputs.DOCKERHUB_REPOSITORY }}:buildcache
          cache-to: type=registry,ref=${{ inputs.DOCKERHUB_REPOSITORY }}:buildcache,mode=max
